### ISSUE TITLE
Wrong URL in custom package repository?

### ISSUE THREAD

**Issue by netique** [scholaempirica/reschola#44]
Installing package with `install.packages("reschola")` fails, even if `.Rprofile` is correctly edited and loaded or `options(repos = c(getOption("repos"), "scholaempirica" = "scholaempirica.github.io/drat"))
install.packages("reschola")` printed.

The issue can be solved with adding a `HTTPS` protocol to custom repo path:
 `https://scholaempirica.github.io/drat`

EDIT:
With changed `.Rprofile`, I am unable to download any packages that are not included in our `drat` repo.

**Comment by petrbouchal** [comment]
Thanks!

Yup - the https bit is where is the solution I had found and edited the code - glad it worked. (I had updated the test code in #2 to that effectd.) I will update the documentation as per #42. 

Ad .Rprofile: I suspect that is because yours does not set an explicit CRAN mirros?

mine reads like this:
```
# set a CRAN mirror
local({r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com"
options(repos=r)})

# add drat repo
local({r <- getOption("repos")
r["scholaempirica"] <- "https://scholaempirica.github.io/drat"
options(repos=r)})
```
If you run `getOption("repos")` you should see something like
```
                                CRAN                          petrbouchal 
          "https://cran.rstudio.com" "https://scholaempirica.github.io/drat"
```

**Comment by netique** [comment]
Ad .Rprofile: I suspect that is because yours does not set an explicit CRAN mirros?

EXACTLY....
