### ISSUE TITLE
Dedoc with RStudio addin

### ISSUE THREAD

**Issue by netique** [scholaempirica/reschola#74]
Using `redoc` RStudio addin (which calls `redoc:::dedoc_to_new_file()`), the .Rmd output is wrongly encoded and does not support further rendering/knitting to .docx output. However, using `redoc::dedoc("foo.docx", to = "foo.Rmd")` works like a charm and as intended.

**Comment by petrbouchal** [comment]
This may or may not be fixed in my fork at petrbouchal/redoc. The fork contains some big fixes that the author has not accepted yet, but if that does not resolve the issue and you have an OK workaround I would suggest using this workaround, as the bug seems to be platform/machine specific. You can also update the documentation to that effect or I can do that.
